// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: interface.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace TestService {
  public static partial class TestService
  {
    static readonly string __ServiceName = "TestService.TestService";

    static readonly grpc::Marshaller<global::TestService.HealthCheckRequest> __Marshaller_TestService_HealthCheckRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TestService.HealthCheckRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TestService.HealthCheckResponse> __Marshaller_TestService_HealthCheckResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TestService.HealthCheckResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TestService.HelloWorldRequest> __Marshaller_TestService_HelloWorldRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TestService.HelloWorldRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TestService.HelloWorldResponse> __Marshaller_TestService_HelloWorldResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TestService.HelloWorldResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::TestService.HealthCheckRequest, global::TestService.HealthCheckResponse> __Method_HealthCheck = new grpc::Method<global::TestService.HealthCheckRequest, global::TestService.HealthCheckResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HealthCheck",
        __Marshaller_TestService_HealthCheckRequest,
        __Marshaller_TestService_HealthCheckResponse);

    static readonly grpc::Method<global::TestService.HelloWorldRequest, global::TestService.HelloWorldResponse> __Method_HelloWorld = new grpc::Method<global::TestService.HelloWorldRequest, global::TestService.HelloWorldResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HelloWorld",
        __Marshaller_TestService_HelloWorldRequest,
        __Marshaller_TestService_HelloWorldResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TestService.InterfaceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TestService</summary>
    [grpc::BindServiceMethod(typeof(TestService), "BindService")]
    public abstract partial class TestServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TestService.HealthCheckResponse> HealthCheck(global::TestService.HealthCheckRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::TestService.HelloWorldResponse> HelloWorld(global::TestService.HelloWorldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TestService</summary>
    public partial class TestServiceClient : grpc::ClientBase<TestServiceClient>
    {
      /// <summary>Creates a new client for TestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TestService.HealthCheckResponse HealthCheck(global::TestService.HealthCheckRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TestService.HealthCheckResponse HealthCheck(global::TestService.HealthCheckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HealthCheck, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TestService.HealthCheckResponse> HealthCheckAsync(global::TestService.HealthCheckRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheckAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TestService.HealthCheckResponse> HealthCheckAsync(global::TestService.HealthCheckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HealthCheck, null, options, request);
      }
      public virtual global::TestService.HelloWorldResponse HelloWorld(global::TestService.HelloWorldRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HelloWorld(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TestService.HelloWorldResponse HelloWorld(global::TestService.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HelloWorld, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TestService.HelloWorldResponse> HelloWorldAsync(global::TestService.HelloWorldRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HelloWorldAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TestService.HelloWorldResponse> HelloWorldAsync(global::TestService.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HelloWorld, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_HealthCheck, serviceImpl.HealthCheck)
          .AddMethod(__Method_HelloWorld, serviceImpl.HelloWorld).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TestServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_HealthCheck, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TestService.HealthCheckRequest, global::TestService.HealthCheckResponse>(serviceImpl.HealthCheck));
      serviceBinder.AddMethod(__Method_HelloWorld, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TestService.HelloWorldRequest, global::TestService.HelloWorldResponse>(serviceImpl.HelloWorld));
    }

  }
}
#endregion
