//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: interface.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol GKEgRPCService_GKEgRPCServiceTestCall: ClientCallUnary {}

fileprivate final class GKEgRPCService_GKEgRPCServiceTestCallBase: ClientCallUnaryBase<GKEgRPCService_TestRequest, GKEgRPCService_TestResponse>, GKEgRPCService_GKEgRPCServiceTestCall {
  override class var method: String { return "/GKEgRPCService.GKEgRPCService/Test" }
}

internal protocol GKEgRPCService_GKEgRPCServiceHelloWorldCall: ClientCallUnary {}

fileprivate final class GKEgRPCService_GKEgRPCServiceHelloWorldCallBase: ClientCallUnaryBase<GKEgRPCService_HelloWorldRequest, GKEgRPCService_HelloWorldResponse>, GKEgRPCService_GKEgRPCServiceHelloWorldCall {
  override class var method: String { return "/GKEgRPCService.GKEgRPCService/HelloWorld" }
}


/// Instantiate GKEgRPCService_GKEgRPCServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol GKEgRPCService_GKEgRPCServiceService: ServiceClient {
  /// Synchronous. Unary.
  func test(_ request: GKEgRPCService_TestRequest, metadata customMetadata: Metadata) throws -> GKEgRPCService_TestResponse
  /// Asynchronous. Unary.
  @discardableResult
  func test(_ request: GKEgRPCService_TestRequest, metadata customMetadata: Metadata, completion: @escaping (GKEgRPCService_TestResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceTestCall

  /// Synchronous. Unary.
  func helloWorld(_ request: GKEgRPCService_HelloWorldRequest, metadata customMetadata: Metadata) throws -> GKEgRPCService_HelloWorldResponse
  /// Asynchronous. Unary.
  @discardableResult
  func helloWorld(_ request: GKEgRPCService_HelloWorldRequest, metadata customMetadata: Metadata, completion: @escaping (GKEgRPCService_HelloWorldResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceHelloWorldCall

}

internal extension GKEgRPCService_GKEgRPCServiceService {
  /// Synchronous. Unary.
  func test(_ request: GKEgRPCService_TestRequest) throws -> GKEgRPCService_TestResponse {
    return try self.test(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func test(_ request: GKEgRPCService_TestRequest, completion: @escaping (GKEgRPCService_TestResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceTestCall {
    return try self.test(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func helloWorld(_ request: GKEgRPCService_HelloWorldRequest) throws -> GKEgRPCService_HelloWorldResponse {
    return try self.helloWorld(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func helloWorld(_ request: GKEgRPCService_HelloWorldRequest, completion: @escaping (GKEgRPCService_HelloWorldResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceHelloWorldCall {
    return try self.helloWorld(request, metadata: self.metadata, completion: completion)
  }

}

internal final class GKEgRPCService_GKEgRPCServiceServiceClient: ServiceClientBase, GKEgRPCService_GKEgRPCServiceService {
  /// Synchronous. Unary.
  internal func test(_ request: GKEgRPCService_TestRequest, metadata customMetadata: Metadata) throws -> GKEgRPCService_TestResponse {
    return try GKEgRPCService_GKEgRPCServiceTestCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func test(_ request: GKEgRPCService_TestRequest, metadata customMetadata: Metadata, completion: @escaping (GKEgRPCService_TestResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceTestCall {
    return try GKEgRPCService_GKEgRPCServiceTestCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func helloWorld(_ request: GKEgRPCService_HelloWorldRequest, metadata customMetadata: Metadata) throws -> GKEgRPCService_HelloWorldResponse {
    return try GKEgRPCService_GKEgRPCServiceHelloWorldCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func helloWorld(_ request: GKEgRPCService_HelloWorldRequest, metadata customMetadata: Metadata, completion: @escaping (GKEgRPCService_HelloWorldResponse?, CallResult) -> Void) throws -> GKEgRPCService_GKEgRPCServiceHelloWorldCall {
    return try GKEgRPCService_GKEgRPCServiceHelloWorldCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

